### ISSUE TITLE
utf-8 and token error

### ISSUE THREAD

**Issue by anomjohn12** [tidusjar/Threads.Net#1]
hello there.

I am getting an error like this on this line.

`var text = await response.Content.ReadAsStringAsync().ConfigureAwait(false);`

> '"utf-8"' is not a supported encoding name. See the documentation for the Encoding.RegisterProvider method for information on defining a custom encoding.
Parameter name: name

and when i try to get token from api this warning comes

`var token = await api.GetTokenAsync("username", "password");`

> {"message":"Payload returned is null. A server error field_exception occured. Check server logs for details.","status":"fail"}

where do you think i am going wrong can you help me

**Comment by tidusjar** [comment]
Hi, I'll take a look :) This is very much still a work in progress

**Comment by tidusjar** [comment]
Fixed in 1.1.0-alpha

**Comment by anomjohn12** [comment]
Thank you for your attention but the following warning persists despite updating

> '"utf-8"' is not a supported encoding name. See the documentation for the Encoding.RegisterProvider method for information on defining a custom encoding.
Parameter name: name
